import Head from 'next/head'
import { useRef } from 'react'
import Header from '../components/header'
import Breadcrumb from '../components/breadcrumb'
import Vision from '../components/vision'
import About from '../components/about'
import Quote from '../components/quote'
import Contact from '../components/contact'
import Footer from '../components/footer'

export default function Home() {

  const contact = useRef([]);
  const scrollToElement = () => contact.current.scrollIntoView();

  return (
    <div>
      <Head>
        <title>United Lagos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" /> */}
      </Head>
      <div style={{width:'100%'}}>
        <div className='main-breadcrumb'>
          <Header scrollToElement={scrollToElement} custom='#ffffff' />  
          <Breadcrumb />
        </div>
        <Vision />
        <About />
        <Quote />
        <Contact contactRef={contact} />
        <Footer />
      </div>
    </div>
  )
}
