import React from 'react';
import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import { DisplayImage } from '../components/style';

const vision = () => {
    return(
        <>
         <Head>
            <title>United Lagos | Our Vision</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet" /> */}
        </Head>
            <Header custom='#ffffff' />
            <div className='flex apart centralized-v vision-widget'>
                <div>
                    <h1>The Spirit of Lagos</h1>
                    <p>Many educational materials in local languages are often out of date. We work with school leaders and publishers to ensure that students have access to current textbooks that are age appropriate and written in their primary language.</p>
                    <p>—</p>
                    <p>Alonzo F., School Principal</p>
                    <p><i>Principal organizer</i></p>
                </div>
                <DisplayImage 
                    src='/app/Group 13.png'
                    alt='Lagos bus'
                />
            </div>
            <Footer />
        </>
    )
}

export default vision;